#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build/Publish

on:
  push:
    branches: 
      - master

jobs:
  nightly-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Prepare
        id: prep
        run: |
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo ::set-output name=short_sha1::${SHORT_SHA1}
          PLATFORMS=$(cat PLATFORMS)
          echo ::set-output name=platforms::${PLATFORMS}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push base images
        run: /bin/bash arbitrary-users-patch/build_images.sh --push

      - name: Build and push happy path image
        run: /bin/bash arbitrary-users-patch/happy-path/build_happy_path_image.sh --push

      - name: Build and push devfile image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfiles/Dockerfile
          target: registry
          platforms: ${{ steps.prep.outputs.platforms }}
          tags: quay.io/eclipse/che-devfile-registry:nightly,quay.io/eclipse/che-devfile-registry:${{ steps.prep.outputs.short_sha1 }}
          push: true
